// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsWFcgp8fq55Uhz-UP1-ozhC-4ExwRvdY',
    appId: '1:818724916020:web:bfa7063f4450077631b361',
    messagingSenderId: '818724916020',
    projectId: 'fireaddedfirstcli-f0a09',
    authDomain: 'fireaddedfirstcli-f0a09.firebaseapp.com',
    storageBucket: 'fireaddedfirstcli-f0a09.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4BWqkNE1sZjbOhlAS1-tzLgKkIzkSur4',
    appId: '1:818724916020:android:99cc4986e557580831b361',
    messagingSenderId: '818724916020',
    projectId: 'fireaddedfirstcli-f0a09',
    storageBucket: 'fireaddedfirstcli-f0a09.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHI-CJumm2YAmoxsQ57jALSu51cHefQe0',
    appId: '1:818724916020:ios:45027b0d551aff8a31b361',
    messagingSenderId: '818724916020',
    projectId: 'fireaddedfirstcli-f0a09',
    storageBucket: 'fireaddedfirstcli-f0a09.appspot.com',
    iosBundleId: 'com.riphah.fireaddedfirst',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHI-CJumm2YAmoxsQ57jALSu51cHefQe0',
    appId: '1:818724916020:ios:b84ce66367a3a61431b361',
    messagingSenderId: '818724916020',
    projectId: 'fireaddedfirstcli-f0a09',
    storageBucket: 'fireaddedfirstcli-f0a09.appspot.com',
    iosBundleId: 'com.riphah.fireaddedfirst.RunnerTests',
  );
}
